fix error message fd.

diff --git a/bin/kemumaki b/bin/kemumaki
--- a/bin/kemumaki
+++ b/bin/kemumaki
@@ -100,7 +100,7 @@ case "${command}" in
     rpmbuild
     ;;
   *)
-    echo "[ERROR] no such command: ${command}"
+    echo "[ERROR] no such command: ${command}" >&2
     exit 1
     ;;
 esac
